// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: httpgateway.proto
#ifndef GRPC_httpgateway_2eproto__INCLUDED
#define GRPC_httpgateway_2eproto__INCLUDED

#include "httpgateway.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace httpgateway {

class HttpGateway final {
 public:
  static constexpr char const* service_full_name() {
    return "httpgateway.HttpGateway";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::httpgateway::ProduceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>> AsyncProduce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>>(AsyncProduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>> PrepareAsyncProduce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>>(PrepareAsyncProduceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>* AsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::httpgateway::ProduceResponse>* PrepareAsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::httpgateway::ProduceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>> AsyncProduce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>>(AsyncProduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>> PrepareAsyncProduce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>>(PrepareAsyncProduceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, std::function<void(::grpc::Status)>) override;
      void Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>* AsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>* PrepareAsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Produce_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Produce(::grpc::ServerContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Produce() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProduce(::grpc::ServerContext* context, ::httpgateway::ProduceRequest* request, ::grpc::ServerAsyncResponseWriter< ::httpgateway::ProduceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Produce<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Produce() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response) { return this->Produce(context, request, response); }));}
    void SetMessageAllocatorFor_Produce(
        ::grpc::MessageAllocator< ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Produce(
      ::grpc::CallbackServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Produce<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Produce() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Produce() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProduce(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Produce() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Produce(context, request, response); }));
    }
    ~WithRawCallbackMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Produce(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Produce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Produce() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse>* streamer) {
                       return this->StreamedProduce(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Produce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Produce(::grpc::ServerContext* /*context*/, const ::httpgateway::ProduceRequest* /*request*/, ::httpgateway::ProduceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProduce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::httpgateway::ProduceRequest,::httpgateway::ProduceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Produce<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Produce<Service > StreamedService;
};

}  // namespace httpgateway


#endif  // GRPC_httpgateway_2eproto__INCLUDED
