// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: httpgateway.proto

#include "httpgateway.pb.h"
#include "httpgateway.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace httpgateway {

static const char* HttpGateway_method_names[] = {
  "/httpgateway.HttpGateway/Produce",
};

std::unique_ptr< HttpGateway::Stub> HttpGateway::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HttpGateway::Stub> stub(new HttpGateway::Stub(channel, options));
  return stub;
}

HttpGateway::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Produce_(HttpGateway_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HttpGateway::Stub::Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::httpgateway::ProduceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Produce_, context, request, response);
}

void HttpGateway::Stub::async::Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Produce_, context, request, response, std::move(f));
}

void HttpGateway::Stub::async::Produce(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Produce_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>* HttpGateway::Stub::PrepareAsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::httpgateway::ProduceResponse, ::httpgateway::ProduceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Produce_, context, request);
}

::grpc::ClientAsyncResponseReader< ::httpgateway::ProduceResponse>* HttpGateway::Stub::AsyncProduceRaw(::grpc::ClientContext* context, const ::httpgateway::ProduceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProduceRaw(context, request, cq);
  result->StartCall();
  return result;
}

HttpGateway::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HttpGateway_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HttpGateway::Service, ::httpgateway::ProduceRequest, ::httpgateway::ProduceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HttpGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::httpgateway::ProduceRequest* req,
             ::httpgateway::ProduceResponse* resp) {
               return service->Produce(ctx, req, resp);
             }, this)));
}

HttpGateway::Service::~Service() {
}

::grpc::Status HttpGateway::Service::Produce(::grpc::ServerContext* context, const ::httpgateway::ProduceRequest* request, ::httpgateway::ProduceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace httpgateway

